[appendix]
== 比特币白皮书勘误

本附录((("Bitcoin whitepaper", "errata", id="bitcoin-whitepaper-errata")))((("whitepaper (Bitcoin)", "errata", id="whitepaper-errata")))描述了 Satoshi Nakamoto 论文《Bitcoin: A Peer-to-Peer Electronic Cash System》中已知的问题，并附有术语演变以及比特币实际实现与论文描述差异之处的说明。

本文档最初由本书的一位合著者于 2016 年发表，此处重印并加以更新。本勘误中各节的名称对应于 Nakamoto 原始论文中各节的名称。

=== 摘要

____
"最长链不仅作为所见证事件序列的证明，也是它由最大 CPU 算力池产生的证明。"
____

* *实现细节：* 如果链中的每个环节（在比特币中称为"区块"）都是用相同数量的 _proof-of-work_（PoW）构建的，那么最长链将是由最大算力池支持的那条链。然而，比特币的实现方式使得不同区块之间 PoW 的数量可以不同，因此检查的对象不再是"最长链"，而是"展示出最多 PoW 的链"；这通常被简称为"最大工作量链"（most-work chain）。
+
从检查最长链到检查最大工作量链的
https://oreil.ly/XYZzx[变更]
发生在 2010 年 7 月，距比特币最初发布已过去很久：
+
[source,diff]
----
-    if (pindexNew->nHeight > nBestHeight)
+    if (pindexNew->bnChainWork > bnBestChainWork)
----

[role="less_space pagebreak-before"]
* *术语变化：* 早期比特币区块的 PoW 由通用 CPU 生成，但今天的 PoW 生成大多由专用集成电路（ASIC）完成，因此与其说"CPU 算力"，不如更准确地说"算力"，或就生成 PoW 所用的哈希运算而言，简称为"哈希率"。

____
"只要多数 CPU 算力由不合谋攻击网络的节点控制，它们就会生成最长链，并把攻击者甩在身后。"
____

* *术语变化：* 今天"节点"一词指的是全验证节点，即强制执行系统所有规则的程序。今天延长链的程序（和硬件）则被称为"miners"，这一称呼源自 Nakamoto 在论文第 6 节中将其类比为金矿矿工。Nakamoto 期望所有 miner 都是节点，但他发布的软件并不要求所有节点都是 miner。在最初的软件中，节点 GUI 中一个简单的菜单项即可切换开启或关闭挖矿功能。
+
今天的情况是，绝大多数节点并非 miner，许多拥有挖矿硬件的个人也并不通过自己的节点来使用它们（即便那些用自己节点挖矿的人，往往也只在新发现的区块之上短暂挖矿，并不确认其节点是否认可该新区块的有效性）。论文前半部分大多直接使用"nodes"一词，指的是使用全验证节点进行挖矿；后半部分提到"network nodes"，则主要讨论节点即使不挖矿也能做的事情。
* *发表后的发现：* 当新区块产生时，产生该区块的 miner 可以立即开始处理其后续区块的工作，而其他所有 miner 在新区块通过网络传播到他们之前都对此一无所知，因而无法开始相应的工作。这给产出区块多的 miner 相对于产出区块少的 miner 提供了优势，并可被利用形成所谓的 _自私挖矿攻击_（selfish mining attack），使得拥有全网约 30% 哈希率的攻击者能够降低其他 miner 的利润，或许进而迫使他们追随攻击 miner 的策略。因此与其说"多数 CPU 算力由不合谋攻击网络的节点控制"，不如更准确地说"只要合谋攻击网络的节点控制不到全网约 30% 的算力"。

=== 交易

____
"我们((("transactions", "errata in Bitcoin whitepaper", id="transaction-errata")))将一枚电子货币定义为一串数字签名。每位所有者通过对前一笔交易的哈希以及下一位所有者的公钥进行数字签名，并将其附加到该枚货币的末尾，从而将货币转让给下一位所有者。"
____

* *实现细节：* 比特币实现了该体系的一个更一般化的版本——并不直接使用数字签名，而是改用一个"确定性表达式"（deterministic expression）。正如可以用与已知公钥匹配的签名来启用支付一样，满足某个已知表达式的数据也可以启用支付。在比特币中，要花费一枚货币所必须满足的表达式被泛称为"负担"（encumbrance）。迄今为止，比特币中几乎所有的 encumbrance 都要求提供至少一个签名。因此与其说"一串数字签名"，不如更准确地说"一串 encumbrance"。考虑到交易通常有多个输入和多个输出，其结构并不像链，更准确的描述是有向无环((("transactions", "errata in Bitcoin whitepaper", startref="transaction-errata")))图（DAG）。

=== 工作量证明

____
"……我们((("proof-of-work algorithm", "errata in Bitcoin whitepaper", id="proof-errata")))通过在区块中递增一个 nonce 来实现 proof-of-work，直到找到一个使区块哈希具有所需的零位前缀的值。"
____

* *实现细节：* Adam Back 的 Hashcash 实现要求找到一个具有指定数量前导零位的哈希。比特币则将哈希视为一个整数，要求其小于某个指定的整数，这实际上允许指定带小数的位数。

____
"Proof-of-work 本质上是一 CPU 一票。"
____

* *重要说明：* 此处的投票并非针对系统规则，而仅针对交易顺序，以提供"电子货币"不易被双花的保证。论文第 11 节对此有更详细的描述：当中写道："我们考虑攻击者试图比诚实链更快地生成一条替代链的情景。即使做到了这一点，也不会使系统对任意改动敞开大门，比如凭空创造价值或拿走从不属于攻击者的资金。节点不会接受无效交易作为支付，诚实节点也绝不会接受包含此类交易的区块。"

____
"……proof-of-work 难度由一个移动平均值决定，目标是每小时若干区块的平均产出。"
____

* *实现细节：* 实际并未使用移动平均。相反，每第 2,016 个区块的报告生成时间会与某个更早区块的生成时间进行比较，二者之差用于计算调整所依据的平均值。
+
此外，比特币实际实现的均值瞄准的是每两周（而非文中可能暗示的每小时）若干个区块的平均产出。其他已实现的规则可能进一步放缓调整，比如规定每个周期内调整不得将出块速度提高超过 300%，也不得放慢超过((("proof-of-work algorithm", "errata in Bitcoin whitepaper", startref="proof-errata"))) 75%。

=== 回收磁盘空间

____
"一旦((("disk space, reclaiming")))((("reclaiming disk space")))((("blocks", "reclaiming disk space")))一枚货币中的最新交易被埋在足够多的区块之下，其之前已花费的交易便可被丢弃以节省磁盘空间。"
____

* *可能的发表后发现：* 尽管本节描述的 Merkle tree 结构可以证明某笔交易被包含在某个特定区块中，但目前在比特币中没有办法证明某笔交易尚未被花费，除非处理区块链中所有后续数据。这意味着此处描述的方法不能普遍地用于所有节点回收磁盘空间，因为所有新节点都将需要处理全部交易。

=== 简化支付验证

____
"一种((("payment verification", "errata in Bitcoin whitepaper")))((("verifying", "payment", "errata in Bitcoin whitepaper")))抵御此类问题的策略是：在网络节点检测到无效区块时接受其发出的警报，提示用户软件下载完整区块和被警示的交易以确认这种不一致。"
____

* *重要说明：* 尽管已有软件实现了本节的某些部分并称之为简化支付验证（SPV），但目前没有任何一款这样的程序会在检测到无效区块时接受网络节点（全验证节点）发出的警报。这在过去使所谓 SPV 钱包中的比特币面临过风险。

=== 隐私

____
"在((("privacy", "errata in Bitcoin whitepaper")))多输入交易中，仍不可避免地会有某种关联性，因为这必然揭示这些输入归同一所有者所有。"
____

* *发表后的发明：* 如果所有者经常将自己的输入与属于其他所有者的输入混在一起，那么同一交易中的不同输入是否属于同一所有者就不再明确。例如，从公开数据看，Alice 与 Bob 各贡献其一个输入用于向 Charlie 与 Dan 付款，与仅由 Alice 贡献她的两个输入向 Charlie 与 Dan 付款，两者之间并无区别。
+
该技术今天被称为
https://oreil.ly/UBEJX[CoinJoin]，相关实现软件自 2015 年起已在使用。

=== 计算

____
"收款方((("calculations", "errata in Bitcoin whitepaper")))在签名前不久生成一对新的密钥对，并将公钥交给付款方。这可防止付款方提前准备一条区块链，持续在其上运算直到他幸运地领先足够远，然后在那一刻执行交易。"
____

* *发表后的发现：* 收款方在付款方签署交易前不久生成公钥，并不能阻止付款方提前准备一条区块链。早期比特币用户 Hal Finney 发现了这一攻击并对其
https://oreil.ly/kg_Xe[作了描述]："假设攻击者偶尔会生成区块。在他生成的每个区块中，他都包含一笔由其控制的地址 A 转账到其控制的地址 B 的交易。
+
"为欺骗你，当他生成一个区块时，他并不广播它。相反，他跑到你的店里，用他的地址 A 向你的地址 C 付款。你等几秒，没听到任何异常，便交付了商品。此时他广播自己的区块，他的那笔交易便会优先于你的那笔。"
+
该攻击对任何确认数都奏效，有时被称为 Finney 攻击。

'''''

*免责声明：* 本文档的作者并非首先识别出此处所述任何问题的人——他只是将它们汇集到一份文档中。

*许可：* 本勘误文档以
https://oreil.ly/xZeBR[CC0] 1.0 通用公共领域贡献协议发布。

如需查看本书出版((("Bitcoin whitepaper", "errata", startref="bitcoin-whitepaper-errata")))((("whitepaper (Bitcoin)", "errata", startref="whitepaper-errata")))之后的更新，请参阅
https://oreil.ly/ygExa[原始文档]。
